# Default values for gpii-flowmanager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

svc_listen_port: 80
flowmanager_listen_port: 8081
datasource_listen_port: 5984
datasource_hostname: "http://admin:password@couchdb-svc-couchdb.gpii.svc.cluster.local"

node_env: gpii.config.cloudBased.flowManager.production
preferences_url: http://preferences.gpii.svc.cluster.local/preferences/%gpiiKey?merge=%merge

image:
  repository: gpii/universal
  checksum: sha256:652ed9dc86639d51e806356737567336339c9eb675193ba04b2c5346de3bdee6
  pullPolicy: IfNotPresent

rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

issuerRef:
  name: letsencrypt-production
  kind: Issuer

dnsNames:
- flowmanager.test.local

secretKeyRef:
  name: couchdb-secrets
  key: datasource_hostname

ingress:
  disable_ssl_redirect: false

nameOverride: flowmanager

## Optional resource requests and limits for deployment
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources: {}
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  # limits:
  #  cpu: 56
  #  memory: 256Gi
