apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  namespace: monitoring
  name: main
  labels:
    alertmanager: main
spec:
  replicas: 3
  version: v0.9.1
  # Relies on user doing `kubectl port-forward`. Forces
  # all links to what is typically the first instance in
  # the StatefulSet.
  externalUrl: http://localhost:9093
