---


apiVersion: v1
kind: Service
metadata:
  namespace: gpii
  name: couchdb
  labels:
    app: couchdb
spec:
  clusterIP: None
  selector:
    app: couchdb
  ports:
  - name: data
    port: 5984
  - name: admin
    port: 5986

---


apiVersion: v1
kind: Service
metadata:
  namespace: gpii
  name: couchdb-lb
  labels:
    app: couchdb
spec:
  selector:
    app: couchdb
  ports:
  - name: data
    port: 5984
  - name: admin
    port: 5986
