apiVersion: v1
kind: Service
metadata:
  namespace: gpii
  name: preferences
spec:
  selector:
    app: preferences
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081
  type: ClusterIP