apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: gpii
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: webmaster@raisingthefloor.org
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-production
  namespace: gpii
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: webmaster@raisingthefloor.org
    privateKeySecretRef:
      name: letsencrypt-production
    http01: {}
