stages:
  - setup
  - unit-tests
  - dev
  - promote-to-stg
  - stg
  - promote-to-prd
  - prd

setup:
  stage: setup
  script:
    - terraform -version
    - terragrunt -version
    - kubectl version --client
    - kops version
    - helm version --client
    - aws --version
    - jq --version
    - ruby --version
    - bundle version
    - rake --version

unit-tests:
  stage: unit-tests
  script:
    - cd aws/rakefiles/tests
    - rake

dev:
  stage: dev
  script:
    - cd aws/dev
    - bundle install --path "vendor/bundle"
    - rake clobber
    - rake
  after_script:
    # Clean up even if something failed.
    - cd aws/dev
    - rake destroy
    - rake clobber

promote-to-stg:
  stage: promote-to-stg
  script:
    - export DATESTAMP="$(date -u '+%Y%m%d%H%M%S')"  # e.g. 20170603220542. Uses UTC.
    - echo "DATESTAMP is $DATESTAMP"  # So it's visible in the log
    - git tag "deploy-stg-$DATESTAMP"
    # gitlab is not clever enough to clean up an added remote and git complains
    # if we add a remote that already exists.
    - git remote | grep -q "^origin-rw" || git remote add origin-rw git@github.com:gpii-ops/gpii-infra
    - git push --tags origin-rw

stg:
  stage: stg
  script:
    - cd aws/stg
    - rake clobber
    - rake
  environment:
    name: stg

promote-to-prd:
  stage: promote-to-prd
  script:
    - export DATESTAMP="$(date -u '+%Y%m%d%H%M%S')"  # e.g. 20170603220542. Uses UTC.
    - echo "DATESTAMP is $DATESTAMP"  # So it's visible in the log
    - git tag "deploy-prd-$DATESTAMP"
    # gitlab is not clever enough to clean up an added remote and git complains
    # if we add a remote that already exists.
    - git remote | grep -q "^origin-rw" || git remote add origin-rw git@github.com:gpii-ops/gpii-infra
    - git push --tags origin-rw
  when: manual
  allow_failure: false

prd:
  stage: prd
  script:
    - cd aws/prd
    - rake clobber
    - rake
  environment:
    name: prd
