# Default values for backup-exporter
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: google/cloud-sdk
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: backup-exporter

serviceAccountName: ""

DestinationBucket: ""

schedule: "0 0 * * *"
