kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "backup-exporter.name" . }}
  namespace: backup-exporter
  labels:
    app: {{ template "backup-exporter.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  backup.sh: |
    gcloud config set account {{ .Values.serviceAccountName }}
    gcloud auth list
    SNAPSHOTS=$(gcloud compute snapshots list --sort-by=~creationTimestamp --limit=4 --format="value[separator=';'](name,status)"| tail -n2 | grep READY | cut -f1 -d\;)
    DESTINATION_BUCKET={{ .Values.DestinationBucket }}/
    TIMESTAMP=$(date +%s)
    for snapshot in ${SNAPSHOTS}; do
      gcloud -q compute images create image-disk-${snapshot} --source-snapshot ${snapshot}
      gcloud -q compute images export --destination-uri gs://external-backups/${TIMESTAMP}-${snapshot}.raw.gz --image image-disk-${snapshot}
      gsutil -q cp gs://external-backups/${TIMESTAMP}-${snapshot}.raw.gz ${DESTINATION_BUCKET}${TIMESTAMP}-${snapshot}.raw.gz
      gcloud -q compute images delete image-disk-${snapshot}
    done
