apiVersion: v1
kind: Secret
metadata:
  name: {{ template "backup-exporter.fullname" . }}
  labels:
    app: {{ template "backup-exporter.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  gcloud.json: |
    {{- .Values.serviceAccountJson | nindent 4 }}
