{{- if .Values.createCustomResource -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: issuers.certmanager.k8s.io
{{- if and (semverCompare ">=2.10-0" .Capabilities.TillerVersion.SemVer) (.Values.useCrdInstallHook) }}
  annotations:
    "helm.sh/hook": crd-install
{{- end }}
  labels:
    app: {{ template "cert-manager.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: certmanager.k8s.io
  version: v1alpha1
  names:
    kind: Issuer
    plural: issuers
  scope: Namespaced
{{- end -}}
