apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certmerges.certmerge.lecentre.net
  labels:
    app.kubernetes.io/name: {{ include "certmerge-operator.name" . }}
    helm.sh/chart: {{ include "certmerge-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  group: certmerge.lecentre.net
  names:
    kind: CertMerge
    listKind: CertMergeList
    plural: certmerges
    singular: certmerge
  scope: Namespaced
  version: v1alpha1
