# Default values for gpii-preferences.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

svc_listen_port: 80
preferences_listen_port: 8081
datasource_listen_port: 5984

node_env: gpii.config.preferencesServer.standalone.production

image:
  repository: gpii/universal
  checksum: sha256:b9da957b2511ec2c25d1e6054359b0a345c4c14dc7853355054e70bd01fda323
  pullPolicy: IfNotPresent

issuerRef:
  name: letsencrypt-production

dnsNames:
- preferences.test.local

secretKeyRef:
  name: couchdb-secrets
  key: datasource_hostname

ingress:
  disable_ssl_redirect: false

nameOverride: preferences
