apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "flushtokens.name" . }}
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ template "flushtokens.name" . }}
        spec:
          shareProcessNamespace: true
          containers:
          - name: gpii-flushtokens
            image: "{{ .Values.image.repository }}@{{ .Values.image.checksum }}"
            command: [ "/bin/sh", "-c", "/app/scripts/dockerDeleteExpiredAccessTokens.sh; while curl -s -XPOST http://127.0.0.1:15000/healthcheck/ok; do curl -s -XPOST http://127.0.0.1:15000/quitquitquit; done; pkill -9 /usr/local/bin/pilot-agent" ]
            env:
            - name: GPII_COUCHDB_URL
              value: '{{ .Values.couchdbUrl }}'
            # Use '--deleteAll' to delete all of the access tokens
            - name: DELETE_ALL
              value: 'false'
          restartPolicy: OnFailure
