# Default values for couchdb-prometheus-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

exporter_listen_port: 9984
couchdb_uri: http://couchdb-svc-couchdb.default.svc.cluster.local:5984
couchdb_username: admin
couchdb_password: hunter2
couchdb_databases: _all_dbs

image:
  ###repository: gesellix/couchdb-prometheus-exporter
  ###checksum: sha256:a1f388fa250c2c8f3d0a38028fe81e5a43f9e2af4c44b5dbfb28b5e41f87cbd4
  repository: mrtyler/couchdb-prometheus-exporter
  checksum: latest
  pullPolicy: IfNotPresent

## Optional resource requests and limits for deployment
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources: {}
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  # limits:
  #  cpu: 56
  #  memory: 256Gi
