# Default values for couchdb-prometheus-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

exporter_listen_port: 9984
couchdb_uri: http://couchdb-svc-couchdb.default.svc.cluster.local:5984
couchdb_username: admin
couchdb_password: password
couchdb_databases: _all_dbs

image:
  repository: gesellix/couchdb-prometheus-exporter
  checksum: sha256:77a019a7707f581f70239783d0b76500ba25b9382d9ee0702452b0381d5722c2
  pullPolicy: IfNotPresent

## Optional resource requests and limits for deployment
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
   cpu: 25m
   memory: 80Mi
  limits:
   cpu: 25m
   memory: 80Mi
