clusterSize: ${replica_count}

adminUsername: ${couchdb_admin_username}
adminPassword: ${couchdb_admin_password}
cookieAuthSecret: ${couchdb_auth_cookie}

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClass: "standard"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app"
              operator: In
              values:
              - couchdb
        topologyKey: "kubernetes.io/hostname"

resources:
  requests:
    cpu: ${requests_cpu}
    memory: ${requests_memory}
  limits:
    cpu: ${limits_cpu}
    memory: ${limits_memory}
