controller:
  image:
    repository: ${nginx_ingress_repository}
    tag: ${nginx_ingress_tag}
  config:
    server-tokens: "false"
  service:
    loadBalancerIP: ${load_balancer_ip}
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi

defaultBackend:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

rbac:
  create: true
  serviceAccountName: default
