controller:
  image:
    repository: ${nginx_ingress_repository}
    tag: ${nginx_ingress_tag}
  config:
    server-tokens: "false"
  service:
    loadBalancerIP: ${load_balancer_ip}
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi
  metrics:
    enabled: true
  stats:
    enabled: true
  extraContainers:
    - name: prometheus-to-sd
      image: "${prometheus_to_sd_repository}:${prometheus_to_sd_tag}"
      imagePullPolicy: IfNotPresent
      command:
        - /monitor
        - --stackdriver-prefix=custom.googleapis.com
        - --source=nginx-ingress:http://localhost:10254
        - --pod-id=$(POD_NAME)
        - --namespace-id=$(POD_NAMESPACE)
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

defaultBackend:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

rbac:
  create: true
  serviceAccountName: default
