apiVersion: v1
kind: Service
metadata:
  name: flow-manager
  annotations:
    dns.alpha.kubernetes.io/external: "flow-manager.k8s-dev-tyler.gpii.net"
spec:
  selector:
    app: flow-manager
  ports:
  - port: 80
    targetPort: 8081
  type: LoadBalancer # exposed externally
